version: "3"

services:
  drupal-php:
    image: drupal-php
    hostname: drupal-php
    build: php
    environment:
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
      - DATABASE_MASTER=drupal-mariadb-master
      - DATABASE_SLAVE=drupal-mariadb-slave
      - URL=example.com
    volumes:
      - drupal-files:/opt/drupal/web/sites/default/files
    depends_on:
      - drupal-mariadb-master

  drupal-web:
    image: drupal-web
    hostname: drupal-web
    build: nginx
    environment:
      NODE_ENV: production
    ports:
      - "9090:80"
    volumes:
      - drupal-files:/opt/drupal/web/sites/default/files
    depends_on:
      - drupal-php

  drupal-mariadb-master:
    image: mariadb:11.2
    hostname: mariadb-master
    command: --server_id=1 --log-bin --log-basename=master1 --binlog-format=mixed
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      #MARIADB_ROOT_PASSWORD:
      MARIADB_USER:
      MARIADB_PASSWORD:
      MARIADB_DATABASE:
      MARIADB_REPLICATION_USER: replication_user
      MARIADB_REPLICATION_PASSWORD:
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - drupal-mariadb-master:/var/lib/mysql

  drupal-mariadb-slave:
    image: mariadb:11.2
    hostname: mariadb-slave
    command: --server-id=2 --log-basename=master1 --binlog-format=mixed --read-only
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      #MARIADB_ROOT_PASSWORD:
      MARIADB_MASTER_HOST: drupal-mariadb-master
      MARIADB_REPLICATION_USER: replication_user
      MARIADB_REPLICATION_PASSWORD:
      MARIADB_HEALTHCHECK_GRANTS: REPLICA MONITOR
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--replication_io", "--replication_sql", "--replication_seconds_behind_master=1", "--replication"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      drupal-mariadb-master:
        condition: service_healthy
    volumes:
      - drupal-mariadb-slave:/var/lib/mysql

volumes:
    drupal-mariadb-master:
    drupal-mariadb-slave:
    drupal-files: