version: "3"

services:
  drupal-php:
    image: "drupal-php"
    build: php
    environment:
      DATABASE: drupal
      DATABASE_USER: drupal
      DATABASE_PASSWORD: drupalpassword
      DATABASE_HOST: drupal-database
      URL: example.com
    volumes:
      - drupal-files:/opt/drupal/web/sites/default/files
    depends_on:
      - drupal-database


  drupal-web:
    image: drupal-web
    build: nginx
    environment:
      NODE_ENV: production
    ports:
      - "9090:80"
    volumes:
      - drupal-files:/opt/drupal/web/sites/default/files
    depends_on:
      - drupal-php

  drupal-database:
    image: "mariadb:11.2.2-jammy"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupalpassword
    volumes:
      - drupal-database:/var/lib/mysql

volumes:
    drupal-database:
    drupal-files: