apiVersion: v1
kind: Service
metadata:
  name: drupal-mariadb-slave
  labels:
    app: drupal-mariadb-slave
spec:
  type: ClusterIP
  ports:
  - port: 3306
    name: drupal-mariadb-slave
  selector:
    app: drupal-mariadb-slave

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drupal-mariadb-slave
  labels:
    app: drupal-mariadb-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mariadb-slave
  template:
    metadata:
      labels:
        app: drupal-mariadb-slave
    spec:
      hostname: drupal-mariadb-slave
      containers:
      - name: drupal-mariadb-slave
        image: mariadb:11.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_RANDOM_ROOT_PASSWORD
          value: random
        - name: MARIADB_MASTER_HOST
          value: drupal-mariadb-master
        - name: MARIADB_REPLICATION_USER
          value: replication_user
        - name: MARIADB_REPLICATION_PASSWORD
          value: 96Qm9EJ8Ga0eTmSnzQg4NMBn
        - name: MARIADB_REPLICATION_PASSWORD
          value: REPLICA MONITOR