apiVersion: v1
kind: Service
metadata:
  name: drupal-mariadb
  labels:
    app: drupal-mariadb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    name: drupal-mariadb
  selector:
    app: drupal-mariadb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mariadb
  labels:
    app: drupal-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mariadb
  template:
    metadata:
      labels:
        app: drupal-mariadb
    spec:
      hostname: drupal-mariadb
      containers:
      - name: drupal-mariadb
        image: mariadb:11.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: wuXvgleZRwgMj2CasXi7
        - name: MARIADB_DATABASE
          value: drupal       
        - name: MARIADB_USER
          value: drupal
        - name: MARIADB_PASSWORD
          value: tHtEBLSDZNtDBVu0AFUc8
        - name: DATABASE_MASTER
          value: drupal-mariadb