apiVersion: v1
kind: Service
metadata:
  name: drupal-mariadb-slave
  labels:
    app: drupal-mariadb-slave
spec:
  clusterIP: None
  ports:
  - port: 3306
    name: drupal-mariadb-slave
  selector:
    app: drupal-mariadb-slave

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mariadb-slave
  labels:
    type: glusterfs
    app: drupal-mariadb-slave
spec:
  storageClassName: gluster-hostpath
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/glusterfs/microk8s/drupal/mariadb-slave"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mariadb-slave
  labels:
    app: drupal-mariadb-slave
spec:
  storageClassName: gluster-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mariadb-slave
  labels:
    app: drupal-mariadb-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mariadb-slave
  template:
    metadata:
      labels:
        app: drupal-mariadb-slave
    spec:
      hostname: drupal-mariadb-slave
      volumes:
      - name: drupal-mariadb-slave
        persistentVolumeClaim:
          claimName: drupal-mariadb-slave
      containers:
      - name: drupal-mariadb-slave
        image: mariadb:11.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: drupal-mariadb-slave
          mountPath: /var/lib/mysql
        env:
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mariadb-passwords
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mariadb-passwords
              key: MARIADB_REPLICATION_PASSWORD
        - name: MARIADB_MASTER_HOST
          value: drupal-mariadb-master
        - name: MARIADB_REPLICATION_USER
          value: replication_user
        - name: MARIADB_HEALTHCHECK_GRANTS
          value: REPLICA MONITOR
        args: ["--server-id=2", "--log-basename=master1", "--binlog-format=mixed", "--read-only"]