apiVersion: v1
kind: Service
metadata:
  name: drupal-php
  labels:
    app: drupal-php
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: drupal-php
  selector:
    app: drupal-php

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-files
  labels:
    type: glusterfs
    app: drupal-php
spec:
  storageClassName: gluster-hostpath
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/glusterfs/microk8s/drupal/drupal-files"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-files
  labels:
    app: drupal-php
spec:
  storageClassName: gluster-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-php
  labels:
    app: drupal-php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drupal-php
  template:
    metadata:
      labels:
        app: drupal-php
    spec:
      hostname: drupal-php
      volumes:
      - name: drupal-files
        persistentVolumeClaim:
          claimName: drupal-files
      containers:
      - name: drupal-php
        image: harbor.lan:8443/drupal/10-php:10.2.1-php8.3-fpm-alpine3.19
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: drupal-files
          mountPath: /opt/drupal/web/sites/default/files
        env:
        - name: MARIADB_DATABASE
          value: drupal
        - name: MARIADB_USER
          value: drupal
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mariadb-passwords
              key: MARIADB_PASSWORD          
        - name: DATABASE_MASTER
          value: drupal-mariadb-master
        - name: DATABASE_SLAVE
          value: drupal-mariadb-slave
        - name: URL
          value: drupal.k8s
      imagePullSecrets:
      - name: regcred
      tolerations:
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 15
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 15